GITHUB_TOKEN = "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"
OPENAI_API_KEY = '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'
